[supabase]
SUPABASE_URL = "https://smxlfclvevdkikxwbzzs.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNteGxmY2x2ZXZka2lreHdienpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg2MTEwODMsImV4cCI6MjEwNDE4NzA4M30.ucTJcszlvfkLK3Rp49p-pvElEToNIykr375EvoST3Ps"

[groq]
API_KEY = "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"
